### ISSUE TITLE
A suggestion and a question

### ISSUE THREAD

**Issue by jasnow** [programmiersportgruppe/visualisation-utils#2]
Suggestion: Add **Install gnuplot** in the README as prereq.

Question: When I run your examples, the graphs are created but they do not stay open. How do I get them to stay open and not flash open/close?

**Comment by jasnow** [comment]
I figured it out "gnuplot -p".

**Comment by fleipold** [comment]
Thanks for the suggestion it's implemented.  Did you change the script or did you call gnuplot manually to make the -p work? What platform are you using? You could create a new ticket to add a proper parameter. Also, are you aware that you can render to a file and then open that depending on your platform along these lines:

   scatter-plot -o graph.png <stats.dat; open graph.png

**Comment by jasnow** [comment]
Add added this line to my script: **gnuplot -p `ls -1t /tmp/plot-*.plt |head -1`**

**Comment by jasnow** [comment]
My platform is Ubuntu 12.04

**Comment by fleipold** [comment]
I don't have ubuntu to test, but I added the `-p` if `--outfile`  is not specified. It's released as version 0.6. Does it work for you?

**Comment by jasnow** [comment]
>> Does it work for you?

Yes, I see that "-p" is default now if I do not use --outfile.
